Numpy

pip install numpy

In [2]:
import numpy as np 
a = np.array([1,2,3]) 
print (a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


In [6]:
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 4) 
print(a)

[[[[1 2 3 4 5]]]]


In [7]:
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[ 1.+0.j  2.+0.j  3.+0.j]


In [8]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [9]:
list1=[1,2,3,4,5]
list1*5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [10]:
a= np.array([1,2,3])
a*5

array([ 5, 10, 15])

In [15]:
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print('\n\n\n')
a.shape = (3,2) 
print (a)

[[1 2 3]
 [4 5 6]]




[[1 2]
 [3 4]
 [5 6]]


In [16]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
import numpy as np 
a = np.arange(24) 
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [12]:
a.ndim

1

In [14]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
print(a)
print(a.ndim)  

# now reshape it 
b = a.reshape(2,4,3) 
# b = a.reshape(2,4,2) 
print (b) 
# b is having three dimensions
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [26]:
import numpy as np 
l = np.empty([3,2], dtype = int) 
print (l)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
import numpy as np 
x = np.zeros(5) 
print (x)

[ 0.  0.  0.  0.  0.]


In [30]:
import numpy as np 
x = np.zeros((5,5), dtype = np.float64) 
print (x)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [31]:
import numpy as np 
x = np.ones([2,2], dtype = int) 
print (x)

[[1 1]
 [1 1]]


In [15]:
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print (type(a))

<class 'numpy.ndarray'>


In [34]:
import numpy as np 

x = (1,2,3) 
a = np.asarray(x) 
print (a)

[1 2 3]


In [16]:
import numpy as np 
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print (a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [39]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2]
assert isinstance(b, object)
print (b)

[2 4 6]


In [21]:
import numpy as np 

a = np.arange(10) 
b = a[5] #doesnt return the numpy array
print (b)

5


In [22]:
import numpy as np 
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [23]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [24]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[:,1]) 
print (a[:,1:2]) 
print ('\n')  

# Now we will slice all items from the second row 
print ('The items in the second row are:') 
print (a[1,:]) 
print ('\n' )

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[:,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]
[[2]
 [4]
 [5]]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [25]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print (y)

[1 4 5]


In [26]:
#import the pandas library and aliasing as pd
import pandas as pd
s = pd.Series()
print (s)

Series([], dtype: float64)


In [48]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print (s)

0    a
1    b
2    c
3    d
dtype: object


In [29]:
#import the pandas library and aliasing as pd
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[100,101,102,103])
print (s)

In [50]:
import pandas as pd
import numpy as np
data = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data)
print (s)

a    0.0
b    1.0
c    2.0
dtype: float64


In [32]:
#import the pandas library and aliasing as pd
import pandas as pd
import numpy as np
data = {'a' : 0., 'b' : "1", 'c' : 2.}
s = pd.Series(data,index=['b','c','d','a'])
print (s)

b      1
c      2
d    NaN
a      0
dtype: object


In [52]:
import pandas as pd
import numpy as np
s = pd.Series(5, index=[0, 1, 2, 3])
print (s)

0    5
1    5
2    5
3    5
dtype: int64


In [55]:
import pandas as pd
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

#retrieve the first element
print (s['a'])
print(s['a'])
print(s)

1
1
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [56]:
import pandas as pd
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

#retrieve the first three element
print (s[:3])

a    1
b    2
c    3
dtype: int64


In [57]:
import pandas as pd
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

#retrieve the last three element
print (s[-3:])

c    3
d    4
e    5
dtype: int64


In [58]:
import pandas as pd
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

#retrieve multiple elements
print (s[['a','c','d']])

a    1
c    3
d    4
dtype: int64


In [59]:
#import the pandas library and aliasing as pd
import pandas as pd
df = pd.DataFrame()
print (df)

Empty DataFrame
Columns: []
Index: []


In [37]:
import pandas as pd
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [62]:
import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print (df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [63]:
import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print (df)

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0


In [64]:
import pandas as pd
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print (df)

       Age   Name
rank1   28    Tom
rank2   34   Jack
rank3   29  Steve
rank4   42  Ricky


In [65]:
import pandas as pd
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
print (df)

   a   b     c
0  1   2   NaN
1  5  10  20.0


In [66]:
import pandas as pd

d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
      'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
print (df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [67]:
import pandas as pd

d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd']), 
     'three' : pd.Series([10,20,30], index=['a','b','c'])}

df = pd.DataFrame(d)
print ("Our dataframe is:")
print (df)

# using del function
print ("Deleting the first column using DEL function:")
del df['one']
print (df)

# using pop function
print ("Deleting another column using POP function:")
df.pop('two')
print (df)

Our dataframe is:
   one  three  two
a  1.0   10.0    1
b  2.0   20.0    2
c  3.0   30.0    3
d  NaN    NaN    4
Deleting the first column using DEL function:
   three  two
a   10.0    1
b   20.0    2
c   30.0    3
d    NaN    4
Deleting another column using POP function:
   three
a   10.0
b   20.0
c   30.0
d    NaN


In [68]:
import pandas as pd

d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
print (df.loc['b'])

one    2.0
two    2.0
Name: b, dtype: float64


In [53]:
import pandas as pd

d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
print (df.iloc[0])

one    1.0
two    1.0
Name: a, dtype: float64


In [59]:
import pandas as pd

df = pd.DataFrame([[1, 2], [3, 4,5]], columns = ['a','b','c'])
print(df)
df2 = pd.DataFrame([[5, 6], [7, 8,9]], columns = ['a','c','b'],index=[3,4])
print(df2)

df = df.append(df2)
print (df)
df.append()
# df = pd.DataFrame(df)
# df.drop(df.iloc[NaN])
# s = df.dropna()
# print(s)

   a  b    c
0  1  2  NaN
1  3  4  5.0
   a  c    b
3  5  6  NaN
4  7  8  9.0
   a    b    c
0  1  2.0  NaN
1  3  4.0  5.0
3  5  NaN  6.0
4  7  9.0  8.0


In [41]:
import pandas as pd

df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'])

df = df.append(df2)
print(df)
# Drop rows with label 0
df = df.drop(0)

print (df)

   a  b
0  1  2
1  3  4
3  5  6
4  7  8
   a  b
1  3  4
3  5  6
4  7  8
